<?php


/**
 * Skeleton subclass for representing a row from the 'place' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 27 21:15:30 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Place extends BasePlace {

  public function asArray($host)
  {
    return array(
      'category'     => $this->getCategory(),
      'type'         => $this->getCategoryId(),
      'company'      => $this->getCompany(),
      'logo'         => $this->getLogo() ? 'http://'.$host.'/uploads/jobs/'.$this->getLogo() : null,
      'url'          => $this->getUrl(),
      'position'     => $this->getPosition(),
      'location'     => $this->getLocation(),
      'description'  => $this->getDescription(),
      'how_to_apply' => $this->getHowToApply(),
      'expires_at'   => $this->getCreatedAt('c'),
    );
  }
    public function save(PropelPDO $con = null)
    {
      if ($this->isNew())
      {
          $this->setCategoryId(1);
          $this->setLat(10);
          $this->setLng(20);
      }

      return parent::save($con);
    }
} // Place
