<?php


/**
 * Skeleton subclass for representing a row from the 'place' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 27 21:15:30 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Place extends BasePlace {

  public function asArray($currentUserId)
  {
    return array(
      'id'            => $this->getId(),
      'category'      => $this->getCategory(),
      'categoryId'    => $this->getCategoryId(),
      'name'          => $this->getName(),
      'user'          => $this->getsfGuardUser()->getUsername(),
      'userId'        => $this->getUserId(),
      'currentUserId' => $currentUserId,
      'lat'           => $this->getLat(),
      'lng'           => $this->getLng(),
      'description'   => $this->getDescription(),
      'createdAt'     => $this->getCreatedAt('Y-m-d H:i:s')
    );
  }
    public function save(PropelPDO $con = null, $user_id = null)
    {
        if ($this->isNew())
        {
            $this->setUserId($user_id);
        }
      return parent::save($con);
    }
} // Place
